### ISSUE TITLE
关于配置

### ISSUE THREAD

**Issue by GrowingPPP** [dotbalo/k8s-ha-install#1]
你好，我如果想配置只有一个master节点，两个node节点的集群（资源有限）可否参考您的这篇教程，loadbalance节点的角色能否让maste节点充当，还有关于：create-config.sh如果只有一个master节点需要怎么编辑，k8s小白一个，希望得到帮助，谢谢

**Comment by dotbalo** [comment]
@GrowingPPP 您好，是可以的，去除所有高可用配置，VIP也无需配置，单master下，VIP的地址就是master的地址，无需额外配置keepalived等。
