### ISSUE TITLE
关于1.16版本kubenetes二进制安装集成calico网络

### ISSUE THREAD

**Issue by Nick-0314** [dotbalo/k8s-ha-install#2]
作者你好 我这两天刚买了再也不踩坑的kubenetes实战指南   跟着书上安装的时候   （二进制部署） 卡到了集成网络的那一部分    我安装的是1.16.1版本 （是因为我拿到这本书的时候已经出1.16.1了）
然后部署到calico网络  发现根据书中内容无法解决   网上也没有解决方案    请问作者能在github上更新以下1.15和1.16版本二进制安装吗       多谢

**Comment by dotbalo** [comment]
您好，可以贴一下报错吗？你也可以加QQ群，后期方便交流780043119

**Comment by Nick-0314** [comment]
calico的pod无法创建 而且也不知道怎么修改新版本的calico的yaml文件 请问作者有1.16版本二进制安装的实践吗

**Comment by dotbalo** [comment]
1.16版本可能需要calico 3.9以上才可以，如果你集群已经搭建成功了，那报错就可能和集群无关，我用kubeadm 装的集群，calico3.9是可以正常运行的，你可以看下这个文档，https://www.cnblogs.com/dukuan/p/11588004.html，kubeadm能正常运行，二进制应该也没有问题。

**Comment by Nick-0314** [comment]
我kubeadm装使用那个yaml文件也是可以用 但是二进制却不行 我集群搭建完成了  但是calico却不行 
我也怀疑是我yaml文件有问题 您的二进制部署使用的yaml文件和kubeadm使用的yaml文件是一个吗
您可以看一下这个文档 是我搭建集群的文档 
https://github.com/mytting/kubernetes/blob/master/%E4%BA%8C%E8%BF%9B%E5%88%B6%E5%AE%89%E8%A3%851.16%E6%9C%AA%E5%AE%8C%E5%BE%85%E7%BB%AD/v1.16.1-H%20%E9%83%A8%E7%BD%B2%E5%B7%A5%E4%BD%9C%E8%8A%82%E7%82%B9.md

**Comment by dotbalo** [comment]
报错信息有时间贴一下

**Comment by Nick-0314** [comment]
calico-kube-controllers-589945ccc8-ksm6m   0/1     Pending    0          21s
calico-node-5xk9c                          0/1     Init:0/2   0          21s
calico-node-bvdtg                          0/1     Init:0/2   0          21s
calico-node-ldwrs                          0/1     Init:0/2   0          21s

pod的详细信息

Events:
  Type     Reason            Age        From               Message
  ----     ------            ----       ----               -------
  Warning  FailedScheduling  <unknown>  default-scheduler  0/3 nodes are available: 3 node(s) had taints that the pod didn't tolerate.
  Warning  FailedScheduling  <unknown>  default-scheduler  0/3 nodes are available: 3 node(s) had taints that the pod didn't tolerate.
  Normal   Scheduled         <unknown>  default-scheduler  Successfully assigned kube-system/calico-kube-controllers-589945ccc8-ksm6m to node2
  Normal   Pulling           44s        kubelet, node2     Pulling image "calico/kube-controllers:v3.9.2"
  Normal   Pulled            7s         kubelet, node2     Successfully pulled image "calico/kube-controllers:v3.9.2"
  Normal   Created           7s         kubelet, node2     Created container calico-kube-controllers
  Normal   Started           6s         kubelet, node2     Started container calico-kube-controllers
  Warning  Unhealthy         4s         kubelet, node2     Readiness probe failed: Failed to read status file status.json: open status.json: no such file or directory

**Comment by Nick-0314** [comment]
我是下载的这个yaml文件
https://docs.projectcalico.org/v3.9/getting-started/kubernetes/installation/hosted/calico.yaml

**Comment by dotbalo** [comment]
````
curl https://docs.projectcalico.org/v3.10/manifests/calico.yaml -O

POD_CIDR="<your-pod-cidr>" \
sed -i -e "s?192.168.0.0/16?$POD_CIDR?g" calico.yaml

kubectl apply -f calico.yaml
````

**Comment by Nick-0314** [comment]
多谢
